### PR TITLE
don't create validation functions on instantiation

### PR DESCRIPTION
**Pull request by czue**
this removes about 6,000 function declarations from `./manage.py runserver` on commcarehq

### CODE REVIEW

**Comment by czue** [comment]
@dannyroberts

**Comment by dannyroberts** [comment]
No way! This is awesome. Curious how you pinpointed this, and what the overall speed gain (or memory gain?) is to commcarehq from introducing this change.

**Comment by dannyroberts** [comment]
And how was your first experience committing to jsonobject? :)

**Comment by czue** [comment]
I don't think it has a significant impact, unfortunately. I was playing around with `objgraph` yesterday and looking for significant sources of memory usage in our baseline process and this was one simple thing that came up just in terms of number of objects being made (though not necessarily significantly impacting the overall memory footprint). Experience was good!

Here's what I was roughly using as a guide: http://www.lshift.net/blog/2008/11/14/tracing-python-memory-leaks/

**Comment by dannyroberts** [comment]
Just got around to reading that article, and FWIW I think we're using the
same library that he had trouble with, amqp; the result of his personal
investigation there was that since something within amqp overrides
`__del__` and participates in a reference cycle, those objects don't get
cleaned up by the garbage collector. No intuition as to whether that'd hit
us significantly too, just a thought.

**Comment by czue** [comment]
that's funny, I read the entire article without really parsing any of the actual examples he was using. does seem worth looking into.

**Pull request merged**
