### PR TITLE
Add BSD license classifier

### LINKED ISSUE #181: Add license to setup.py
Please add `license="BSD"` to your `setup.py` classifiers so that automated tools can determine the license type of the package.

### PR DESCRIPTION
**Pull request by czue**
closes #181

### CODE REVIEW

**Comment by czue** [comment]
@dannyroberts any guidance on this build error? Some additional set of commands I need to run?

```
=====================================

ERROR: ./.travis/test_cython_files.sh

-------------------------------------

diff --git a/jsonobject/api.c b/jsonobject/api.c

index 9f9114c..c299eac 100644

--- a/jsonobject/api.c

+++ b/jsonobject/api.c

@@ -1,4 +1,4 @@

-/* Generated by Cython 0.29.21 */

+/* Generated by Cython 0.29.23 */

 

 /* BEGIN: Cython Metadata

 {

@@ -12,15 +12,17 @@

 }

 END: Cython Metadata */

 

+#ifndef PY_SSIZE_T_CLEAN

 #define PY_SSIZE_T_CLEAN

+#endif /* PY_SSIZE_T_CLEAN */

 #include "Python.h"

 #ifndef Py_PYTHON_H

     #error Python headers needed to compile C extensions, please install development version of Python.

-------------------------------------

Compiling the C files from scratch shows a difference

The first 20 lines of the diff is shown above

Did you rebuild and commit the changes?  Try running:

    find jsonobject -iname '*.c' -delete

    find jsonobject -iname '*.so' -delete

    python setup.py build_ext --inplace

The command "if [[ $TRAVIS_PYTHON_VERSION > 3.5 ]]; then .travis/test_cython_files.sh; fi" exited with 1.
```

**Comment by dannyroberts** [comment]
I think to fix that you have to run `pip install cython== 0.29.23` (see the first few lines of the diff where the version changes) followed by the "Try running" lines

```
find jsonobject -iname '*.c' -delete
find jsonobject -iname '*.so' -delete
python setup.py build_ext --inplace
```

which should rebuild the cython files. If you commit the changes that should fix the diff.

**Comment by dannyroberts** [comment]
It's admittedly a bummer that that's the responsibility of whoever happens to make a PR after the last time that a new 0.29.x point release of cython is released, but that seems to be how it's set up

**Review by dannyroberts — APPROVED** [review]
Thanks!

**Comment by czue** [comment]
kicked PR build and it's passing now.

**Pull request merged**
