### PR TITLE
Rebuild C files using cython==0.29.28

### PR DESCRIPTION
**Pull request by PeterJCLaw**
This seems to be needed to get CI to pass and presumably adds support for more recent Python versions.

Generated using the same lines as `.travis/test_cython_files.sh` does, on Python ~2.7~ 3.10.

I'm not personally a Cython expert so I'm not really able to comment on the actual changes here.

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
Meta: is updating these files for every version of Cython the expected approach? Would it make sense to pin to a (minor) version of Cython and perhaps have the test know how to ignore patch-level version number changes?

**Comment by dannyroberts** [comment]
Thanks @PeterJCLaw. Yeah this is a known annoyance. We'd be happy to accept a contribution that improved it. I think basically all the relevant context is captured in these two comments https://github.com/dimagi/jsonobject/pull/182#issuecomment-849104054 and https://github.com/dimagi/jsonobject/pull/183#issuecomment-849661066 from the last time exactly this happened.

**Comment by dannyroberts** [comment]
Since it's been a while since we did this, I confirmed that I get the same output that you (and the tests on the PR) did when I run

```
find jsonobject -iname '*.c' -delete
find jsonobject -iname '*.so' -delete
python setup.py build_ext --inplace
```
locally.

I'm going to also edit the name of this PR to include the cython version so it's more easily identifiable in the future.

**Comment by dannyroberts** [comment]
I'll also update the matrix of python versions this is tested against to only include non-deprecated versions of python

**Comment by dannyroberts** [comment]
Thanks for your contribution @PeterJCLaw!

**Pull request merged**
