### PR TITLE
support dynamic object property types

### PR DESCRIPTION
**Pull request by snopoke**
@dannyroberts what do you think?.

### CODE REVIEW

**Comment by snopoke** [comment]
Would be very useful in UCR and one or two other places

**Comment by snopoke** [comment]
@czue could replace the UCR factories

**Comment by czue** [comment]
looks nice!

**Comment by dannyroberts** [comment]
Hey @snopoke, this is great. Some thoughts:

- In the interests of keeping jsonobject small, something like this feels too specialized to be part of the library. I'd be a fan of having it inside commcare-hq.
- The syntax/naming/API feels a little clunky to me, in that it takes a little while to figure out what it's trying to do. The target syntax I'd love would be something like this:
```python
class Penguin(JsonObject):
    animal_name = TypeProperty('penguin')

class Tiger(JsonObject):
    animal_name = TypeProperty('tiger')

class ZooPen(JsonObject):
    # this is reminiscent of languages that have algebraic types, which is kind of what this is
    animal = ObjectProperty(Pinguin | Tiger)
    # alternatively, we could have something like 
    # animal = ObjectProperty(CompoundType(Pinguin, Tiger))
```

(If we come upon a syntax that seems intuitive and generic enough, it might change my mind about not belonging inside jsonobject)

**Comment by dannyroberts** [comment]
@snopoke did you get any further on this or just dropping for now?

**Comment by snopoke** [comment]
I did play around a bit but haven't come up with anything workable yet.

**Pull request closed without merging**
